### PR TITLE
Modified ForEachAsync to release items as processed

### PR DESCRIPTION
**Pull request by sergii-sakharov**
#2644

Memory leak is caused by WhenAll that expects all of the tasks in the
bulk operations to complete to further invoke done() delegate in
ForEachAsync. Referencing all of the tasks in WhenAll causes them to
prevent GC from collecting processed items.

### CODE REVIEW

**Comment by Mpdreamz** [comment]
ty @sergii-sakharov this is the better solution rather then assuming `Task,WhenAll` wont OOM. 👍 

Im merging this locally because not awaiting that new async method has some implications for Exceptions.

Also adding `.Wait()` extension methods that will behave and rethrow exceptions as expected (relates #2634 )

**Comment by sergii-sakharov** [comment]
I'm trying to write a test for ForEachAsync at the moment but it is internal, and as far as I can tell there is no InternalsVisibleTo settings. Is it ok to elevate it to public or should I try to test the issue via BulkAll invocation as a full-blown integration test?

**Comment by Mpdreamz** [comment]
I think this warrants an `InternalsVisisbleTo` as much as I tried to avoid having to set it 👍

**Comment by sergii-sakharov** [comment]
Just to confirm - to enable InternalsVisibleTo I had to sign Tests assembly - used the same key as Nest assebly (build/keys/..). I hope that does not affect any of the builds...

**Comment by sergii-sakharov** [comment]
Unfortunately it turned out to be far from straightforward - Tests assembly has a dependency on nuget package Semantic Versioning (https://github.com/adamreeve/semver.net) which is not strongly named for some reason. I am not sure how straightforward would be to sign the dll after nuget restore - E.g. sn.exe is bundled with tooling but it works only with already signed/delay signed assemblies. Tool that is needed for signing unsigned one is AssemblyLinker (al.exe) which as far as I can tell might be platform specific. There is also an option of using something like https://www.nuget.org/packages/Nivot.StrongNaming/
Right now I am at a loss - will try to think of other ways tomorrow.

Additionaly - on original topic - I had an impression that the root cause of having to cut-off async-await chain propagating to the api level is IObserver/IObservable interfaces. They don't seem to be designed with async/await in mind. Which made me curious what is the reason for using them?

**Comment by Mpdreamz** [comment]
One other solution would be be to link the extension into the Test project but that is really only a viable solution in the new csproj world and we're not ready to switch to that before Rider supports it.

Closing this in favor of https://github.com/elastic/elasticsearch-net/pull/2651 where I added some commits to this PR specifically around exception handling. Would love a quick review @sergii-sakharov !

**Pull request closed without merging**
