### PR TITLE
Deprecate Alias on GetAlias and GetAliases

### PR DESCRIPTION
**Pull request by russcam**
Closes https://github.com/elastic/elasticsearch-net/issues/2194

### CODE REVIEW

**Comment by Mpdreamz** [comment]
LGTM :+1:

**Comment by russcam** [comment]
Will _port_ to `master`

**Comment by tabro** [comment]
@gmarz @russcam @Mpdreamz I believe that this PR may have caused an issue with NEST throwing a deserilazation error when performing the following code on a non-existing alias when providing AllowedStatusCodes.:

 ```
await ElasticClient.GetAliasAsync(d => d
                                .RequestConfiguration(r => r
                                .AllowedStatusCodes((int)HttpStatusCode.NotFound)
                                .CancellationToken(CancellationToken.None))
                   .Name("does-not-exist"))
                   .ConfigureAwait(false);
```

Removing the `.AllowedStatusCode(404)` makes NEST correctly return an empty list of aliases. In previous versions this would throw an exception as expected.

**Comment by tabro** [comment]
Stacktrace:

```
Elasticsearch.Net.UnexpectedElasticsearchClientException : Error converting value "alias [does-not-exist] missing" to type 'System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.Dictionary`2[System.String,Nest.AliasDefinition]]'. Path 'error', line 1, position 41.
  ----> Newtonsoft.Json.JsonSerializationException : Error converting value "alias [does-not-exist] missing" to type 'System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.Dictionary`2[System.String,Nest.AliasDefinition]]'. Path 'error', line 1, position 41.
  ----> System.ArgumentException : Could not cast or convert from System.String to System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.Dictionary`2[System.String,Nest.AliasDefinition]].
   at Elasticsearch.Net.Transport`1.<RequestAsync>d__15`1.MoveNext() in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Transport\Transport.cs:line 150
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nest.ElasticClient.<Nest-IHighLevelToLowLevelDispatcher-DispatchAsync>d__220`4.MoveNext() in C:\Users\russ\source\elasticsearch-net-2.x\src\Nest\ElasticClient.cs:line 0
```

**Comment by russcam** [comment]
@tabro do you have an example json response where this throws?

**Comment by russcam** [comment]
@tabro I've looked into this further. This change didn't introduce the error that you're seeing, that throws an exception on the commit c5206075fb2701ab61251f1e7f1a9b5da9a7e219 prior to this change.

By allowing a status code in `.AllowedStatusCodes()`, you're telling NEST that if the status code comes back as one in the range `>= 200` and `< 300` or as one in the allowed status codes, then the response is _valid_ and the call is _successful_. At this point, NEST will deserialize the body of the response into the strong type for the request made, which in this case is `IGetAliasesResponse`. This throws an exception as the response looks like

```
HTTP/1.1 404 Not Found
Content-Type: application/json; charset=UTF-8
Content-Length: 67

{
  "error" : "alias [does-not-exist] missing",
  "status" : 404
}
```
and the way alias responses are handled is to [first deserialize to a rather verbose `Dictionary<string, Dictionary<string, Dictionary<string, AliasDefinition>>>` structure.](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Nest/Indices/AliasManagement/GetAliases/ElasticClient-GetAliases.cs#L75)

I'd recommend not setting `.AllowedStatusCodes((int)HttpStatusCode.NotFound)` then either

- check `.IsValid` on the response to know if the response is valid, optionally checking the status code for 404 if this is particular response you want to handle
- set `.ThrowExceptions()` on `ConnectionSettings` and handle the thrown exception in the case of a 404.

**Pull request merged**
