### PR TITLE
update Bullseye to 3.0.0-rc.1

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by adamralph** [comment]
@Mpdreamz FYI this version contains https://github.com/adamralph/bullseye/issues/230

**Comment by adamralph** [comment]
@Mpdreamz would it help if I sent PR's to those branches? It's in my interest to have the RC being used in anger, so I'm happy to do that for you.

**Comment by russcam** [comment]
No worries @adamralph, I got it

**Comment by russcam** [comment]
ported to 7.x, 6.x and 5.x

**Pull request merged**
