### PR TITLE
Sticky Connection Pool

### PR DESCRIPTION
**Pull request by Romanx**
See #1810

Not ready for merging and requires feedback. There's one skipped test which I wasn't sure how to do using your test framework, 

If you could take a look and provide feedback if their is a way. If not it might be worth investing in making a way as it's a slightly more advanced use case than the other tests I found, hopefully the test explains itself well enough, otherwise just ask.

Test can be found in this commit 8d1906a683e007e42429b05c5b1f83b8f1e285ba

### CODE REVIEW

**Comment by Mpdreamz** [comment]
Hi @Romanx we are all travelling and attending [elasticon](https://www.elastic.co/elasticon/conf/2016/sf) the coming days so we might take a tad longer then usual to review this PR.

Can't wait to dig in though :+1:

**Comment by Mpdreamz** [comment]
Thank you for taking the challenge @Romanx :+1:  merged this in today :smile:

**Comment by Romanx** [comment]
@Mpdreamz Thanks for letting me have a stab, hopefully it all makes sense. Sorry about the formatting of the commit, didn't realise I didn't have the editor config plugin installed!

**Comment by Romanx** [comment]
@Mpdreamz did you get to look at the skipped test? I struggled with finding a way to do what I wanted to test with the current test framework, if there's a way i'd be willing to fix up that test

**Pull request merged**
