### PR TITLE
Fix #4289 low level client index http method generation wrong

### LINKED ISSUE #4289: 7.5.0 fails to index documents using low level client.
**NEST/Elasticsearch.Net version**: 7.5.0

**Elasticsearch version**: 7.4.2 & 7.5.0

**Description of the problem including expected versus actual behavior**:
We upgraded our clients this morning from 7.4.2 to 7.5.0 and we had two tests failing. This one occurs after we try to create an error index for documents that failed to index.

Please note this index is created in a previous call:
```cs
 var createResponse = await _client.Indices.CreateAsync(workItem.NewIndex + "-error", d => d.Map(md => md.Dynamic(false))).AnyContext();
            
```

```cs
string document = JsonConvert.SerializeObject(new {
                failure.Index,
                failure.Id,
                gr.Version,
                gr.Routing,
                gr.Source,
                failure.Cause,
                failure.Status,
                gr.Found,
            });
            var indexResponse = await _client.LowLevel.IndexAsync<VoidResponse>(workItem.NewIndex + "-error", PostData.String(document));
```

```json
[405] PUT /employees-v2-error/_doc?pretty=true
 {
   "Cause": {
     "headers": {},
     "root_cause": null
   },
   "Found": true,
   "Id": "5dfa29b22da6ff00851bc366",
   "Index": "employees-v2",
   "Routing": null,
   "Source": {
     "age": 99,
     "companyId": "5dfa29b22da6ff00851bc365",
     "createdUtc": "2019-12-18T13:29:22.4686Z",
     "id": "5dfa29b22da6ff00851bc366",
     "isDeleted": false,
     "lastReview": "0001-01-01T00:00:00",
     "location": "37.0365416105075,-57.4688381317392",
     "nextReview": "0001-01-01T00:00:00+00:00",
     "phoneNumbers": [],
     "updatedUtc": "2019-12-18T13:29:22.4686Z",
     "yearsEmployed": 0
  },  
 "Status": 400,
  "Version": 1
 }
 {
   "error" : "Incorrect HTTP method for uri [/employees-v2-error/_doc?pretty=true] and method [PUT], allowed: [POST]",
   "status" : 405
 }
```

I tried going through the diff between the two versions but it was massive. I didn't see anything that really stood out of what would have changed in the low level client.

### PR DESCRIPTION
**Pull request by Mpdreamz**
We used to always send POST which is not right either but the server
accepted it. Now that we have a new format and transform to the old
format in the interim we only picked up PUT for all which is not correct
for index operations without an id.

This bug affects the low level client only, NEST sends the right HttpMethod based on whether an Id is provided or not.

### CODE REVIEW

**Comment by niemyjski** [comment]
LGTM

**Comment by Mpdreamz** [comment]
One failing test due to #4280 unrelated, merging this in.

**Comment by Mpdreamz** [comment]
ported to `master`

**Comment by Mpdreamz** [comment]
cherry-picked to `7.5` will spin a new release.

**Comment by Mpdreamz** [comment]
Released https://github.com/elastic/elasticsearch-net/releases/tag/7.5.1 thanks for reporting as always @niemyjski !

**Comment by Mpdreamz** [comment]
Deprecated the `7.5.0` release of `Elasticsearch.Net` on nuget in favor of `7.5.1`. 

cc @codebrain @russcam

**Pull request merged**
