### PR TITLE
typo

### PR DESCRIPTION
**Pull request by RustyF**

### CODE REVIEW

**Comment by codebrain** [comment]
Hi @RustyF - thanks for the contribution - would you mind signing the CLA: [https://www.elastic.co/contributor-agreement](https://www.elastic.co/contributor-agreement)?

I can then approve and merge your change.

Thanks!

**Comment by RustyF** [comment]
I've signed the agreement

**Comment by russcam** [comment]
Sorry to be a pain @RustyF, would it be possible to update the source file from which the asciidoc file has been generated too? The source file in question is https://github.com/elastic/elasticsearch-net/tree/6.x/src/Tests/Aggregations/WritingAggregations.doc.cs (_linked at the top of the asciidoc file_).

**Comment by russcam** [comment]
Updated WritingAggregations source and merged

**Comment by russcam** [comment]
Thanks @RustyF !

**Pull request merged**
