### PR TITLE
Remove duplication description on document

### PR DESCRIPTION
**Pull request by adonaiOhesed**
Remove duplication description of `ClientCertificate`.

### CODE REVIEW

**Comment by codebrain** [comment]
@adonaiOhesed - thanks for your commit.

In order to accept this commit we ask that you sign our CLA:
https://www.elastic.co/contributor-agreement

Please also note that the file you are editing is generated from a C# file as per the file header:

```
////
IMPORTANT NOTE
==============
This file has been generated from https://github.com/elastic/elasticsearch-net/tree/6.x/src/Tests/Tests/ClientConcepts/Connection/ConfigurationOptions.doc.cs. 
If you wish to submit a PR for any spelling mistakes, typos or grammatical errors for this file,
please modify the original csharp file found at the link and submit the PR with that change. Thanks!
////
```

Could you please include the change to this file as well?

Thanks!

**Comment by russcam** [comment]
I think the change to remove the duplication is more involved. The two headers relate to the following two methods:

https://github.com/elastic/elasticsearch-net/blob/652108717722dcfc5ef530f5f3708838f659dbc8/src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs#L484-L496

The method parameters are not currently included in the documentation, but we could consider adding them to disambiguate?

**Comment by adonaiOhesed** [comment]
It is my honor to take part in the elastic community.

I agree with Russ Cam's opinion and it is hard to find a change to edit in
a file `
https://github.com/elastic/elasticsearch-net/tree/6.x/src/Tests/Tests/ClientConcepts/Connection/ConfigurationOptions.doc.cs
`.

Thank you!

2019년 5월 7일 (화) 오전 11:00, Russ Cam <notifications@github.com>님이 작성:

**Comment by codebrain** [comment]
Closed this PR and submitted https://github.com/elastic/elasticsearch-net/commit/39cb86a9b6caa704de903c5995937b92aecac4a4 with the change.

Credited the original author, thanks again @adonaiOhesed

**Comment by codebrain** [comment]
Ported to `master` and `7.x`

**Pull request closed without merging**
