### PR TITLE
IMultiGetOperation can now be deserialized

### PR DESCRIPTION
**Pull request by abibell**
MultiGetOperation can now be deserialized as MultiGetOperationDescriptor<object> is now default
JsonConverter.
Resolved https://github.com/elastic/elasticsearch-net/issues/1415
Added unit tests to verify the outcome.

### CODE REVIEW

**Comment by gmarz** [comment]
Thank you @abibell.  LGTM :+1: 

There are definitely more instances where round trip serialization fails within the client.  Part of our plan for NEST 2.0 is to go over all of our mappings/types, as well as re-working our [unit/integration tests](https://github.com/elastic/elasticsearch-net/tree/2.0/src/Tests/Nest.Tests.Literate) which will hopefully catch all of these instances.

Side note: would you mind installing [EditorConfig](https://visualstudiogallery.msdn.microsoft.com/c8bccfe2-650c-4b42-bc5c-845e21f96328) for future PRs?  This will fix the formatting/indentation differences without affecting the preferences on other projects.

**Comment by abibell** [comment]
@gmarz I shall do the editor config next time. Yes I came across and reported 2 so far. Are we better off managing the whole query syntax using xsd or lexical grammar Which will generate perfect working code always? For version 2.0, I mean. Hman errors are due to use handcrafting these things.

**Comment by gmarz** [comment]
@abibell Yes we are!  That's something we've been brain storming on for a while now but it comes with a handful of challenges.  We first toyed with the idea of using JSON schema, but it had too many limitations and could not accurately represent the Elasticsearch query DSL.  For instance, you could use pattern properties to represent variable property names, but you aren't able to do things like enforce the existence of a single occurence, etc...

Our idea at the moment is to create a reference implementation using something like Typescript which we could generate our class and interfaces from, and document any parts that require custom serialization.  This would need to be maintained just like the REST spec is today.

Unfortunately though, with all the things already on our plate for 2.0, this will likely be more of a 3.0 thing...

If you have any thoughts/ideas on this, we would love to hear them.

**Comment by abibell** [comment]
I am keen to do that. I will create an Issue so we can track the progress and list all the limitations, so we can address them.

**Pull request merged**
