### PR TITLE
Fix bug with case-sensitive header comparisions

### PR DESCRIPTION
**Pull request by JoJo2406**
https://github.com/elastic/elasticsearch-net/issues/5938

### CODE REVIEW

**Review by stevejgordon — APPROVED** [review]
LGTM, thanks

**Comment by stevejgordon** [comment]
Thanks for submitting this @JoJo2406. Would you mind signing the CLA above and we can get this merged?

**Comment by JoJo2406** [comment]
@stevejgordon Signed the CLA

**Comment by stevejgordon** [comment]
Thanks again for this contribution @JoJo2406. I'm going to run it through some other tests with a view to releasing a patch ASAP.

**Pull request merged**
