### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by stuartleeks**

### CODE REVIEW

**Comment by russcam** [comment]
Thanks @stuartleeks, that's a terrible typo 😭  Would you mind signing the CLA so we can pull it in?

**Comment by stuartleeks** [comment]
done :-)

**Comment by russcam** [comment]
Thanks! Sorry to be a pain, would you also be able to update it in https://github.com/elastic/elasticsearch-net/tree/6.x/src/Tests/ClientConcepts/LowLevel/GettingStarted.doc.cs ? The asciidoc file is generated from that source, so will only end up being overwritten on the next doc generation!

**Comment by stuartleeks** [comment]
I'm getting a 404 on that path...

**Comment by stuartleeks** [comment]
I'm still getting 404 for : https://github.com/elastic/elasticsearch-net/tree/6.x/src/Tests/ClientConcepts/LowLevel/GettingStarted.doc.cs

**Comment by russcam** [comment]
How about https://github.com/elastic/elasticsearch-net/blob/6.x/src/Tests/Tests/ClientConcepts/LowLevel/GettingStarted.doc.cs#L67 ?

**Comment by stuartleeks** [comment]
bingo - done!

**Comment by russcam** [comment]
Thanks @stuartleeks!

**Pull request merged**
