### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by jiatann**

### CODE REVIEW

**Comment by stevejgordon** [comment]
Thanks, @jiatann. Are you able to sign the CLA, please, and I can merge this in?

**Review by stevejgordon — APPROVED** [review]
LGTM

**Comment by jiatann** [comment]
Hey @stevejgordon I just signed, not sure when it will reflect on this page?

**Comment by stevejgordon** [comment]
@jiatann Unfortunately, it's not reflected on our end. Can you please try signing it again?

**Comment by jiatann** [comment]
Just did again with the Github username as `jiatann`.

**Comment by stevejgordon** [comment]
@jiatann I'm afraid it's still showing as not signed on our end.

**Comment by crazytan** [comment]
Hmm can you check if the CLA check is working correctly on your end? This is the signed document: 
[Please_DocuSign_Individual_Contributor_Licen.pdf](https://github.com/elastic/elasticsearch-net/files/10982781/Please_DocuSign_Individual_Contributor_Licen.pdf)

**Comment by stevejgordon** [comment]
@jiatann I'm seeking support from our infra team to see if we can identify why this isn't being picked up as signed.

**Comment by gtback** [comment]
cla/check

**Comment by jiatann** [comment]
Thanks! Appreciate it

**Comment by gtback** [comment]
Looks like you're set now. I think the issue was that you signed a CLA before with the same email address but a different GitHub username, and the system is not designed to handle changes to GitHub usernames this way. I was able to change it on the backend and the checker now accepted your contribtion.

Thanks for contributing to the project, @jiatann !

**Comment by stevejgordon** [comment]
Thanks for your patience @jiatann! I'll merge this now.

Thanks also for your help @gtback!

**Pull request merged**
