### PR TITLE
Fix fuzziness for QueryStringQuery

### PR DESCRIPTION
**Pull request by MiniGab**

### CODE REVIEW

**Comment by karmi** [comment]
Hi @MiniGab, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch-net/pull/2114.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by MiniGab** [comment]
Hello @karmi done!

**Comment by gmarz** [comment]
LGTM!  Thanks for the PR @MiniGab :+1:

**Comment by russcam** [comment]
Will backport to 2.x in bwc way

**Pull request merged**
