### PR TITLE
Wrapped the contract after user-adjustable settings

### PR DESCRIPTION
**Pull request by bytenik**

### CODE REVIEW

**Comment by jimsorock** [comment]
@Mpdreamz @bytenik is there an example on how to use/override this contract resolver?

**Comment by bytenik** [comment]
What do you mean? What are you trying to accomplish?

**Comment by bytenik** [comment]
@jimsorock What do you mean? What are you trying to accomplish?

**Comment by jimsorock** [comment]
Trying to replace the contract resolver. I know when setting up the client that I can add json converters, but I was wondering how this fixed the issue in #701.

**Comment by bytenik** [comment]
You can replace the resolver with one that passes through requests for contracts for a NEST type to a NEST resolver.

**Comment by jimsorock** [comment]
Ok but where does that replace actually happen? Do I just subclass my own contract resolver from the new SettingsContractResolver?

**Pull request merged**
