### PR TITLE
Improve DefaultIndex documentation

### PR DESCRIPTION
**Pull request by zandiarash**
without defining the default index it does not work.
I was struggling for some minutes to make it work.

### CODE REVIEW

**Comment by russcam** [comment]
The Default index is mentioned on line 179, but we could possibly call it out in its own section at the end of `Connecting`, and before `Indexing`, since it is a common setting to use:

https://github.com/elastic/elasticsearch-net/blob/master/readme.md#connecting

Did you want to update the PR to reflect this? Please can you also sign the [CLA](https://www.elastic.co/contributor-agreement)? This is required before we can accept the PR. Thanks!

**Comment by Arashz22** [comment]
> The Default index is mentioned on line 179, but we could possibly call it out in its own section at the end of `Connecting`, and before `Indexing`, since it is a common setting to use:
> 
> https://github.com/elastic/elasticsearch-net/blob/master/readme.md#connecting
> 
> Did you want to update the PR to reflect this? Please can you also sign the [CLA](https://www.elastic.co/contributor-agreement)? This is required before we can accept the PR. Thanks!

Yes You are right, It is already mentioned on line 179.
but I think it become more simpler for a user who just wanna start to use Elastic and do not have time to read the full document, some one who is following step by step with examples.
Yes I want to reflect that.
I've also singed CLA.

**Comment by russcam** [comment]
I appreciate your point, but I would prefer if the `DefaultIndex` were called out in its own section, and the example included the `.Index(...)`, the same as the others, with a comment to the right, to use the `DefaultIndex`. Something like

```c#
var response = client.Search<Tweet>(s => s
    .Index("mytweetindex") //or specify index via settings.DefaultIndex("mytweetindex");
    .From(0)
    .Size(10)
    .Query(q => q
        .Term(t => t.User, "kimchy") || q
        .Match(mq => mq.Field(f => f.User).Query("nest"))
    )
);
```

and

```c#
var request = new SearchRequest
{
    Index = "mytweetindex", //or specify index via settings.DefaultIndex("mytweetindex");
    From = 0,
    Size = 10,
    Query = new TermQuery { Field = "user", Value = "kimchy" } || 
            new MatchQuery { Field = "description", Query = "nest" }
};

var response = client.Search<Tweet>(request);
```

This brings the search examples in line with the Indexing examples.

**Comment by zandiarash** [comment]
Pretty cool,  you have a better Idea, I've edited my PR according your view.

**Comment by russcam** [comment]
Thanks. Looks like the CLA checker cannot find your record; does your commit use an email address that is linked to your GitHub account?

**Comment by zandiarash** [comment]
you're welcome.
sorry I had changed my username after singing CLA.
now I've singed a new CLA with the current username [zandiarash]
and this is my Email address : arashz44 [att] gmail.com

**Comment by russcam** [comment]
@zandiarash Looks like the CLA checker still cannot find a record for you. Does the git commit have an email address that is linked to your GitHub account? The email address can be private

**Comment by zandiarash** [comment]
Please look at [this](http://arashzandi.ir/myfiles/sign.pdf) (I have signed it again).
Thanks.

**Comment by codebrain** [comment]
Thanks @zandiarash

**Comment by codebrain** [comment]
Ported to `7.x`

**Comment by zandiarash** [comment]
@codebrain My pleasure.

**Pull request merged**
