### PR TITLE
Fix/response :heart:

### PR DESCRIPTION
**Pull request by Mpdreamz**
Give all the responses some ❤️ 

As per #2299 be more consistent responses with returning empty collections vs null on responses. We did this sporadically but not consistently.
Now that we dropped .NET 4.0 we can make the response IEnumerable and Dictionaries IReadOnly*

Made sure all the interfaces only define getters and not setters

### CODE REVIEW

**Comment by Mpdreamz** [comment]
Can you explain why you wonder that @gmarz? Interested to hear your thoughts on this.

**Comment by gmarz** [comment]
@Mpdreamz Robustness principle http://stackoverflow.com/questions/17170/when-to-use-ilist-and-when-to-use-list

> On the other hand, when returning an object out of a function, you want to give the user the richest possible set of operations without them having to cast around.

Previously the richest types would be `List<T>` and `Dictionary<T>`, and now with this PR `ReadOnlyCollection<T>` and `ReadOnlyDictionary<T>`.

**Comment by Mpdreamz** [comment]
Not sure how I feel about returning the concrete types since they expose a lot of operations we dont want to expose e.g `searchResponse.Documents.Add()`. I generally agree with Postel's law but I feel the concrete types set wrong expectations. Also it ties us down. 

Need to sleep on this :)

**Comment by Mpdreamz** [comment]
@gmarz @russcam  rebased against master and fixed the flakey tests. 

Still some integration test failures but they are unrelated to this branch.

**Comment by russcam** [comment]
Will have a look at this today @Mpdreamz

**Comment by russcam** [comment]
7 failing integration tests:

- Tests.XPack.Security.User.PutUser.PutUserRunAsApiTests.ReturnsExpectedIsValid [FAIL]
- Tests.XPack.Security.User.PutUser.PutUserRunAsApiTests.HandlesStatusCode [FAIL]
- Tests.XPack.Security.Role.PutRole.PutRoleRunAsApiTests.HandlesStatusCode [FAIL]
- Tests.XPack.Security.Role.PutRole.PutRoleRunAsApiTests.ReturnsExpectedIsValid [FAIL]

related to the param for shield run as #2394 

- Tests.Indices.StatusManagement.Upgrade.UpgradeApiTests.ReturnsExpectedIsValid [FAIL]
- Tests.Indices.StatusManagement.Upgrade.UpgradeApiTests.HandlesStatusCode [FAIL]

related to allow_no_indices #2397

- Tests.Indices.Monitoring.IndicesShardStores.IndicesShardStoresApiTests.AssertResponse [FAIL]

not sure why this one is failing right now.  `Expected collection not to be empty.`

**Comment by russcam** [comment]
LGTM - would be good to have some Coding Standards unit tests to ensure that this is the case across all `IResponse` types

**Comment by Mpdreamz** [comment]
The IndicesShardResponse was an easy fix, the property now needed an explicit [JsonProperty], squashing and merging this one in.

**Pull request merged**
