### PR TITLE
Support detect_noop in NEST #1587

### PR DESCRIPTION
**Pull request by robertlyson**
Hi Guys,

This is fix for https://github.com/elastic/elasticsearch-net/issues/1587.
Also I've created PR to address this in api spec https://github.com/elastic/elasticsearch/pull/14004.

### CODE REVIEW

**Comment by gmarz** [comment]
Awesome, thanks @robertlyson.  But since #14004 was merged, it would be better to run the code generator to pick up on `detect_noop` as a query string param.

**Comment by gmarz** [comment]
Nevermind, just realized it was merged into ES 2.x and master, which isn't what the develop branch is pointed at.  In that case, we can just manually add it to https://github.com/elastic/elasticsearch-net/blob/develop/src/CodeGeneration/CodeGeneration.LowLevelClient/ApiEndpoints/update.json, then run the code generator.

**Comment by robertlyson** [comment]
I see, so I'll update it manually, run and will be back with an update.

**Comment by robertlyson** [comment]
Update done. Hope it's fine now.

**Comment by gmarz** [comment]
LGTM!

**Pull request merged**
