### PR TITLE
ConcreteTypeSelector method on Scroll

### LINKED ISSUE #1682: Inheritance from abstract type not working
I've got an abstract base class of type `Activity` and subtypes of a variety of types, including `Searched`.

For mappings, I fluent-mapped `Activity` but was forced when fluent-mapping `Searched` to remap everything mapped on `Activity`.

On the storage side, I do for example `client.Index<Activity>(instanceOfSearched, x => x.Index("Activities").Type(typeof(Searched)))`.

When I search, using `client.Search<Activity>(x => x.Indices("Activity").AllTypes().MatchAll())`, I get `JsonSerializationException`s based around an inability to instantiate `Activity` because it is abstract. It doesn't seem to notice that the stored type is actually a `Searched`.

### PR DESCRIPTION
**Pull request by bytenik**
Fixes #1682.

Corrects #1684 PR which was against wrong branch.

### CODE REVIEW

**Comment by gmarz** [comment]
Thanks @bytenik

**Comment by bytenik** [comment]
Any chance of getting this merged? I'd like to be able to pick up this NuGet from your MyGet even if you're not ready to release to NuGet yet.

**Comment by russcam** [comment]
Hey @bytenik, I'm tidying up the branches to rename (branch move and delete)
- `2.0` to `master`
- `develop` (current 1.x client) to `1.x`

and as a consequence, closed this PR as a result of deleting the remote `develop` branch, sorry! I've reinstated the branch to keep track of the open PRs but feel free to close this PR and open a new one with the change against  `1.x` :smile:

**Comment by bytenik** [comment]
See #1689.

**Comment by bytenik** [comment]
Pretty pretty please merge in #1689 soon. :smile:

**Pull request closed without merging**
