### PR TITLE
Asciidoc documentation into 2.x

### PR DESCRIPTION
**Pull request by russcam**
The feature/documentation branch is in a position where it would provide value to appear on the elastic docs site for the 2.x client, on a progession over perfection basis. A summary of the changes:

- references AsciiDoc.dll library located in `src/lib/dnx451`. I will put this up on github and publish to nuget to reference from there when it is good for alpha _(it works for our current purposes but is **limited** and can only output asciidocs for the moment)_. This library is used to modify the asciidocs generated from literate tests to perform such actions as adding attribute entries, section titles for usage pages, etc.

- The structure of the asciidocs has been verified with [the docs generation process](https://github.com/elastic/docs) using

```bash
./build_docs.pl --doc ~/docs/asciidoc/index.asciidoc
```
where `~` is the project root

- Corrected the spelling of some directory names in the Tests project e.g. `ClientConcepts/HighLevel/Inference`, and moved the files to the new directory

- Tidy up and elaborated descriptions for different client options, adding cross reference links where useful

- Usage examples for all Query DSL and Aggregations calls

### CODE REVIEW

**Comment by Mpdreamz** [comment]
:balloon: :tada: :fireworks: :cake: 

Decent docs! Only 4 years in the making :smile: 

This new documentation that'll be part of elastic.co is gonna rock! Functionally everything looks good to me to merge however I have some prerequisites before merging this into the `master` and `2.x` integration branches.

* If AsciiDoc is not in a shape you want to publish it to nuget (prerelease works too here), we need to move the source under Litterateur itself so we can iterate over it. I much rather we publish this under a new github org that we're all part of and throw it on nuget as a prerelease package though, no need to goldplate before opensourcing. 

* Since this is a huge feature PR, I think this needs to be resend from a new branch where you cherry-pick all the actual commits, getting rid of the merge commits, squash them to a degree that makes sense, create a single asciidoc generation commit and send a new PR. This will greatly simplify pulling it into master as well

**Comment by gmarz** [comment]
Awesome work @russcam !  

> Since this is a huge feature PR, I think this needs to be resend from a new branch where you cherry-pick all the actual commits, getting rid of the merge commits, squash them to a degree that makes sense, create a single asciidoc generation commit and send a new PR. This will greatly simplify pulling it into master as well

Would just rebasing against 2.x then squashing to a single commit be the same thing?

**Comment by Mpdreamz** [comment]
that would not get rid of the merge commits with 2.x AFAIK

**Comment by russcam** [comment]
> If AsciiDoc is not in a shape you want to publish it to nuget (prerelease works too here), we need to move the source under Litterateur itself so we can iterate over it. I much rather we publish this under a new github org that we're all part of and throw it on nuget as a prerelease package though, no need to goldplate before opensourcing.

Happy to release to github under an org we can all work on it on - just letting you know it's a little messy in places. Feel free to slash and burn :smile: 

I'll cherry pick the commits out and squash them into one commit for the PR :+1:

**Comment by russcam** [comment]
Closing to open a cherry-picked PR :+1:

**Pull request closed without merging**
