### PR TITLE
Added fields block (docvalue_fields) to SuggestOption #4148

### PR DESCRIPTION
**Pull request by Treno1**
Copied from Hit.cs

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @Treno1, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/elasticsearch-net/pull/4149.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by Mpdreamz** [comment]
HI @Treno1 this LGTM, mind signing the CLA with the email from the commit ?

**Comment by Treno1** [comment]
Signed, sorry for delay

**Comment by russcam** [comment]
Add `docvalue_fields` to `SuggestUsage` tests. Thanks for the PR, @Treno1 👍

**Comment by russcam** [comment]
ported to 7.x and master

**Pull request merged**
