### PR TITLE
add store to timestamp field mapping #1533

### PR DESCRIPTION
**Pull request by KodrAus**
#1533  Any unit tests to implement?

### CODE REVIEW

**Comment by gmarz** [comment]
Thanks for the PR @KodrAus ! I left one minor comment.

We have a few [unit tests for the timestamp field](https://github.com/elastic/elasticsearch-net/blob/develop/src/Tests/Nest.Tests.Unit/Core/Map/TimestampField/TimestampFieldTests.cs).  It would be great if you could include the `store` field in those tests as well.

Also, would you mind signing the [CLA](https://www.elastic.co/contributor-agreement/)?

**Comment by KodrAus** [comment]
I've signed the CLA. Thanks for linking to the unit tests, I'll make the changes and add tests

**Comment by gmarz** [comment]
Excellent, thank you!  One other nitpick I just noticed ^^.

**Comment by KodrAus** [comment]
How's this looking now? It should be verifying that store is not serialized in `TimestampFieldUsingExpression` and that it is in `TimestampFieldUsingString`

**Comment by gmarz** [comment]
LGTM!  Thanks again @KodrAus

**Comment by KodrAus** [comment]
No worries! I'm trying to get more involved in the ES community, since I've been mooching off it for years

**Pull request merged**
