### PR TITLE
Fixed NoopPropertyVisitor

### PR DESCRIPTION
**Pull request by orange-bird**
Small fix for keyword attribute parser in NoopPropertyVisitor

### CODE REVIEW

**Comment by Mpdreamz** [comment]
eek! good catch! LGTM

**Comment by karmi** [comment]
Hi @orange-bird, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch-net/pull/2710.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by orange-bird** [comment]
> Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?
Just added missing e-mail address.

**Comment by karmi** [comment]
Hi @orange-bird, the CLA check still fails, you might have a typo in your company address used in the Git commit, can you look into that?

**Comment by orange-bird** [comment]
Hi @karmi. Yes, it's typo in domain name. Sorry for this. Is it possible to correct?

**Comment by karmi** [comment]
@orange-bird, no worries, and yes, it's very easy to correct, and probably makes sense for you to fix it on your machine :)

So, first you need to set [your username](https://help.github.com/articles/setting-your-username-in-git/) and [your e-mail](https://help.github.com/articles/setting-your-email-in-git/):

```bash
git config --global user.name "Billy Everyteen"
git config --global user.email "your_email@example.com"
```

Then, "amend" the commit while resetting the author information:

```bash
git commit --amend --reset-author
```

Finally, force push the commit again, it should end up here with the correct information:

```bash
git push --force
```

Ping us with a comment, that should also trigger the CLA check.

**Comment by orange-bird** [comment]
Looks OK now.  Thanks for help.

**Comment by russcam** [comment]
Thanks for submitting @orange-bird!

**Comment by russcam** [comment]
- ported to 5.x in 2f250486f970567ad1f3ad2f0c2739beacb73107

Not required to port to 2,x; `text` and `keyword` are 5.x +

**Pull request merged**
