### PR TITLE
Add additional properties on ServerError.Error

### LINKED ISSUE #2355: Add missing properties to Error property on ServerError
Add Phase and Grouped to Error property on ServerError

Example:
```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parse_exception",
        "reason" : "failed to parse date field [-1m] with format [strict_date_optional_time||epoch_millis]"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "project",
        "node" : "Uo6PBln_QrmD8Y9o1NKdQw",
        "reason" : {
          "type" : "parse_exception",
          "reason" : "failed to parse date field [-1m] with format [strict_date_optional_time||epoch_millis]",
          "caused_by" : {
            "type" : "illegal_argument_exception",
            "reason" : "Parse failure at index [2] of [-1m]"
          }
        }
      }
    ],
    "caused_by" : {
      "type" : "parse_exception",
      "reason" : "failed to parse date field [-1m] with format [strict_date_optional_time||epoch_millis]",
      "caused_by" : {
        "type" : "illegal_argument_exception",
        "reason" : "Parse failure at index [2] of [-1m]"
      }
    }
  },
  "status" : 400
}
```

Add Line and Col

Example:

```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parsing_exception",
        "reason" : "[terms] unknown token [END_ARRAY] after [numberOfCommits]",
        "line" : 9,
        "col" : 7
      }
    ],
    "type" : "parsing_exception",
    "reason" : "[terms] unknown token [END_ARRAY] after [numberOfCommits]",
    "line" : 9,
    "col" : 7
  },
  "status" : 400
}
```

### PR DESCRIPTION
**Pull request by russcam**
Closes #2355

### CODE REVIEW

**Comment by Mpdreamz** [comment]
In core they can attach any random property to Exceptions to innerXContent. 

These properties only apply to: https://github.com/elastic/elasticsearch/blob/7560101ec73331acb39a042bde6130e59e4bb630/core/src/main/java/org/elasticsearch/action/search/SearchPhaseExecutionException.java#L137

We can union all the additional properties under `ServerError` but I am wondering if we can do something smarter here.

**Comment by russcam** [comment]
Perhaps capture them in an `.AdditionalDetails` dictionary on `ServerError.Error`?

**Comment by Mpdreamz** [comment]
I think that be better, we already have some others on `ServerError` that would be candidates of bumping down.

**Comment by Mpdreamz** [comment]
Should this be a blocker for release? cc @gmarz @russcam

**Comment by russcam** [comment]
I don't think so @mpdreamz

**Comment by Mpdreamz** [comment]
LGTM tetst

**Comment by russcam** [comment]
look at after 6.x release

**Comment by Mpdreamz** [comment]
This is now part of the work on #2929

**Pull request closed without merging**
