### PR TITLE
Boosted non-exhaustive enum deserialization

### LINKED ISSUE #7729: ElasticsearchClient.GetScript is broken
**Elastic.Clients.Elasticsearch version**: 8.1.0

**Elasticsearch version**: 8.5.2

**.NET runtime version**: Framework 4.7.2

**Operating system version**:

**Description of the problem including expected versus actual behavior**:

ElasticsearchClient.GetScript seems to alwyas throw an exception

**Steps to reproduce**:

Run this code

```
// This call returns successfully
var response = _elasticsearchClient.PutScript("my-script", s => s
    .Script(a => a
        .Language(ScriptLanguage.Painless)
        .Source("doc['id'].value")
    )
);

// This call throws
var script = _elasticsearchClient.GetScript(new GetScriptRequest("my-script"));
```

Expected behavior: Successful completion of GetScript

Actual behavior: This exception
```
Unhandled Exception: Elastic.Transport.UnexpectedTransportException: Constructor on type 'Elastic.Clients.Elasticsearch.ScriptLanguage' not found. ---> System.MissingMethodException: Constructor on type 'Elastic.Clients.Elasticsearch.ScriptLanguage' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at Elastic.Clients.Elasticsearch.Serialization.EnumStructConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in /_/src/Elastic.Clients.Elasticsearch/Serialization/EnumStructConverter.cs:line 18
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAll[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.ReadAllUsingOptions[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Stream utf8Json, JsonSerializerOptions options)
   at Elastic.Clients.Elasticsearch.Serialization.SystemTextJsonSerializer.Deserialize[T](Stream stream) in /_/src/Elastic.Clients.Elasticsearch/Serialization/SystemTextJsonSerializer.cs:line 67
   at Elastic.Transport.DefaultResponseBuilder`1.SetBody[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType) in /home/runner/work/elastic-transport-net/elastic-transport-net/src/Elastic.Transport/Components/Pipeline/DefaultResponseBuilder.cs:line 193
   at Elastic.Transport.DefaultResponseBuilder`1.ToResponse[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, Dictionary`2 headers, Stream responseStream, String mimeType, Int64 contentLength, IReadOnlyDictionary`2 threadPoolStats, IReadOnlyDictionary`2 tcpStats) in /home/runner/work/e
lastic-transport-net/elastic-transport-net/src/Elastic.Transport/Components/Pipeline/DefaultResponseBuilder.cs:line 61
   at Elastic.Transport.HttpWebRequestTransportClient.Request[TResponse](RequestData requestData) in /home/runner/work/elastic-transport-net/elastic-transport-net/src/Elastic.Transport/Components/TransportClient/HttpWebRequestTransportClient.cs:line 103
   at Elastic.Transport.DefaultRequestPipeline`1.CallProductEndpoint[TResponse](RequestData requestData) in /home/runner/work/elastic-transport-net/elastic-transport-net/src/Elastic.Transport/Components/Pipeline/DefaultRequestPipeline.cs:line 219
   at Elastic.Transport.DefaultHttpTransport`1.Request[TResponse](HttpMethod method, String path, PostData data, RequestParameters requestParameters) in /home/runner/work/elastic-transport-net/elastic-transport-net/src/Elastic.Transport/DefaultHttpTransport.cs:line 164
   --- End of inner exception stack trace ---
   at Elastic.Transport.DefaultHttpTransport`1.ThrowUnexpectedTransportException[TResponse](Exception killerException, List`1 seenExceptions, RequestData requestData, TResponse response, RequestPipeline pipeline) in /home/runner/work/elastic-transport-net/elastic-transport-net/src/Elastic.Transport/DefaultHt
tpTransport.cs:line 328
   at Elastic.Transport.DefaultHttpTransport`1.Request[TResponse](HttpMethod method, String path, PostData data, RequestParameters requestParameters) in /home/runner/work/elastic-transport-net/elastic-transport-net/src/Elastic.Transport/DefaultHttpTransport.cs:line 177
   at Elastic.Clients.Elasticsearch.ElasticsearchClient.DoRequest[TRequest,TResponse,TRequestParameters](TRequest request, Action`1 forceConfiguration) in /_/src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient.cs:line 217
   at Elastic.Clients.Elasticsearch.ElasticsearchClient.GetScript(GetScriptRequest request) in /_/src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs:line 1985
```

### PR DESCRIPTION
**Pull request by YohDeadfall**
So, instead of using very slow reflection and trying to optimize it using an array pool a static like member can be used for structs till .NET 7. How it works in the end? The JIT produces code which calls `GetString` and immediately returns that value because it's smart enough to detect wrappers.

It also fixes #7729.

### CODE REVIEW

**Comment by technige** [comment]
Thank you for your submission. We will review this in due course as and when someone is available on the team to do so.

**Comment by flobernd** [comment]
Thanks for this enhancement as well!

Instead of manually adding this interface and the corresponding implementation to every "EnumStruct", it probably makes sense to implement this as a generic optimization to our code generator. I'll keep this PR open for now and push the regenerated files to your branch when I'm done.

**Comment by YohDeadfall** [comment]
Same thoughts, but couldn't get where the generator is. If it would be open sourced then anyone can fix such kind of issue and do improvements.

**Comment by flobernd** [comment]
The code generator repositories are highly coupled to our internal workflow, so opening them up would be a non-trivial task. However, I'm happy to transfer this optimization to the generator project, if possible 🙂

**Comment by YohDeadfall** [comment]
Yeah, that's fine too, but having something open sourced is better (for example, a schema stored in some repo which then can be consumed by build tools here and by other clients).

**Review by flobernd — APPROVED** [review]

**Pull request merged**
