### PR TITLE
Implement client examples (2020-02-27 to 2020-04-01)

### PR DESCRIPTION
**Pull request by codebrain**
Closes: https://github.com/elastic/elasticsearch-net/issues/4461

- Update program to provide a hint to alternatives_report.json location. Suggesting https://raw.githubusercontent.com/elastic/built-docs/master/raw/en/elasticsearch/reference/master/alternatives_report.json as the example path.

### CODE REVIEW

**Comment by codebrain** [comment]
Completion of the https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-reindex.html examples relies on merge of https://github.com/elastic/elasticsearch-net/pull/4470

**Comment by codebrain** [comment]
Looks like https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-update.html was already implemented, thanks @russcam

**Comment by codebrain** [comment]
Its getting close to where I think some JSON pattern matching could be implemented to construct a useful set of default changes (searches as POST, template index settings prefixed with "index.", queries automatically converted to long form etc...)

Not sure what the thoughts are @Mpdreamz @russcam - its a close call, I am tempted to see what the next round of examples holds and then look into a decent example-wide refactoring at that point.

**Comment by Mpdreamz** [comment]
> Not sure what the thoughts are @Mpdreamz @russcam - its a close call, I am tempted to see what the next round of examples holds and then look into a decent example-wide refactoring at that point.

++ lets discuss these at the start of the new round of examples :)

**Comment by codebrain** [comment]
> There are some client changes in here do these need to be backported?

Already backported in https://github.com/elastic/elasticsearch-net/pull/4470 - I cherry picked into here to complete the example.

**Pull request merged**
