### PR TITLE
added Fields support in TopHitsAggregation

### PR DESCRIPTION
**Pull request by V1tOr**

### CODE REVIEW

**Comment by karmi** [comment]
Hi @V1tOr, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch-net/pull/2659.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by V1tOr** [comment]
hi @karmi, 
Done!

**Comment by V1tOr** [comment]
hi @gmarz,

sorry for the late reply. it should be all god now.

cheers.

**Comment by Mpdreamz** [comment]
ported to `5.x` and `master`

**Comment by Mpdreamz** [comment]
The port to master and 5.x and master was a tad overzealous 

```
[FAIL] Tests.Aggregations.Metric.TopHits.TopHitsAggregationUsageTests.ReturnsExpectedIsValid: Expected boolean to be True because Invalid NEST response built from a unsuccessful low level call on POST: /project/project/_search?pretty=true
# Audit trail of this API call:
 - [1] BadResponse: Node: http://ipv4.fiddler:9200/ Took: 00:00:00.3238589
# ServerError: ServerError: 400Type: parsing_exception Reason: "Unknown key for a START_ARRAY in [fields]."
# OriginalException: System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData)
# Request:
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
# Response:
<Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
, but found False.
```

**Pull request merged**
