### PR TITLE
Update to .NET Core RC2

### PR DESCRIPTION
**Pull request by phenixdotnet**
Hi.
please find a PR with all projects ported to .NET RC2.
- All projects build only Nest.Litterateur has errors.
- Some dependencies has been updated to allow targeting .NET Core RC2
- Unit tests are ok on .NET Core but failed on Full .NET

### CODE REVIEW

**Comment by Mpdreamz** [comment]
🎉 🎈 🍰 👍 

Thanks for this PR @phenixdotnet, this is awesome.

**Comment by gmarz** [comment]
@phenixdotnet indeed, this is awesome, thank you!  Will pull this down in the coming days.

**Comment by phenixdotnet** [comment]
@Mpdreamz , @gmarz : You're welcome :)
Most of the work was done with your version for .NET Core RC 1.

I didn't check why NEST.Litterateur doesn't build (the error is related to missing runtime but seem very strange).
Also unit tests fails when running on Full .NET framework and I didn't investigate why.

And thanks to you for this awesome lib :)

**Comment by russcam** [comment]
This is awesome @phenixdotnet , thanks for submitting :+1: 

I'll have a look at the build failures

**Comment by Strandedpirate** [comment]
I got this Nest.Litteratuer to compile with this in project.json. It was just missing `Microsoft.NETCore.App` as a dependency.


    "netcoreapp1.0": {
      "buildOptions": {
        "define": [
          "DOTNETCORE"
        ]
      },
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0-rc2-3002702"
        },
        "System.IO.FileSystem": "4.0.1-rc2-24027",
        "Microsoft.CodeAnalysis.CSharp": "1.3.0-beta1-20160429-01"
      },
      "imports": [ "dnxcore50", "portable-net45+win8" ]
    }

**Comment by russcam** [comment]
[I've pulled this into the dotnet-rc2 branch](https://github.com/elastic/elasticsearch-net/tree/feature/dotnet-rc2) and also updated the FAKE build scripts to use the new tooling.

**Comment by russcam** [comment]
All unit tests and integration tests pass on the dotnet-rc2 branch

```shell
.\build.bat
```

```shell
.\build.bat Integrate 5.0.0-alpha3
```

**Comment by tugberkugurlu** [comment]
Is there any updates on this to get it to .NET Core 1.0.0?

**Comment by russcam** [comment]
@tugberkugurlu Yes, we're looking to put out a release this week

**Comment by gmarz** [comment]
Closing in favor of #2149

**Pull request closed without merging**
