### PR TITLE
Remove duplicated properties

### PR DESCRIPTION
**Pull request by DanAtkinson**
Changes to remove duplicates on https://github.com/elastic/elasticsearch-net/blob/master/docs/client-concepts/connection/configuration-options.asciidoc.

### CODE REVIEW

**Comment by russcam** [comment]
Thanks for opening @DanAtkinson. This change is probably better handled in the DocsGenerator, to deduplicate the overloaded methods when generating the asciidoc labelled list. Would you like to tackle this? I _think_ it would just need a change in

https://github.com/elastic/elasticsearch-net/blob/1eb3928c82fb9b3364505c865970244a941dc217/src/DocGenerator/AsciiDoc/GeneratedAsciidocVisitor.cs#L313

to distinct by Label too.

**Comment by DanAtkinson** [comment]
@russcam Thanks. I'll take a look. I haven't used the DocsGenerator but it _should_ be fairly straightforward to run, change, test, and verify.

**Comment by russcam** [comment]
Doc generation can be run from the build script in the root of the repository

```
.\build documentation
```

**Comment by russcam** [comment]
Hi @DanAtkinson, I went ahead and made the change to  `GeneratedAsciidocVisitor`, and merged this in. Thanks again 👍

**Pull request merged**
