### PR TITLE
Set MaxRetryException on task in RetryRequestAsync

### LINKED ISSUE #1645: MaxRetryException thrown from RequestHandlerAsync is not catchable
`RetryRequestAsync` calls `ThrowMaxRetryExceptionWhenNeeded`, but returns a `Task`.  If you try to `await` this method, the exception is not catchable because it is thrown rather than set on the `Task`.

### PR DESCRIPTION
**Pull request by Entroper**
See #1647, this is a re-open on `1.x`.  Fixes #1645.

Note I'm still working with my employer on signing the contributor agreement.

### CODE REVIEW

**Comment by Mpdreamz** [comment]
Thanks @Entroper anxious to pull this one in, keep us posted on the CLA progress :+1:

**Comment by Mpdreamz** [comment]
Hey Entroper, 

Whats the status on CLA?

Thanks!

**Comment by Entroper** [comment]
@Mpdreamz I've signed the CLA as of today.

**Comment by Mpdreamz** [comment]
No now the ball is in our court, we are all travelling to [elasticon](https://www.elastic.co/elasticon/conf/2016/sf) the coming days but hopefully we find some time where we can review this and do a maintenance release for `1.x`. 

Looking forward to reviewing this one :smile:

**Comment by Mpdreamz** [comment]
Closing this because I was unable to trap this bug in a test to verify this PR 

See also: https://github.com/elastic/elasticsearch-net/issues/1645#issuecomment-193283450

If you can give me some information on how to reproduce please let me know so we can reopen this.

**Pull request closed without merging**
