### PR TITLE
pending elastic/elasticsearch#23009 distance_type will be removed as …

### PR DESCRIPTION
**Pull request by Mpdreamz**
…parameter in its entirety

elastic/elasticsearch#23009

### CODE REVIEW

**Comment by codebrain** [comment]
Waiting on the Elasticsearch PR still... documentation for 6.0 still contains this parameter, so leaving alone for now.

**Comment by russcam** [comment]
Thoughts on closing this, @Mpdreamz @codebrain ? We can pick it up if/when https://github.com/elastic/elasticsearch/pull/23009 gets merged.

**Comment by codebrain** [comment]
@russcam  - Close it, it is very ancient now!

**Comment by gmarz** [comment]
👋

**Comment by russcam** [comment]
Closing this for now, as the PR https://github.com/elastic/elasticsearch/pull/23009 appears to be stalled. Can always reopen on a later date.

**Pull request closed without merging**
