### PR TITLE
Change RequestConfiguration.ThrowExceptions to bool? (#3231)

### PR DESCRIPTION
**Pull request by ivan-sam**

### CODE REVIEW

**Comment by ivan-sam** [comment]
This PR fixes #3231 - undesired behavior when overriding one request configuration setting caused some other (not nullable) settings to override unintentionally associated connection settings just because they got their default values in constructor: e.g. changing request's content type caused request's throw exceptions setting to be set to default(bool) - false. Integration tests added for checking the case.

**Comment by ivan-sam** [comment]
Checked source code.
For branch 5.x I believe there's only EnableHttpPipelining property is affected, cause IRequestConfiguration does not contain ThrowExceptions property.

Fix may be very simple if public contracts should be preserved:
```
--- a/src/Elasticsearch.Net/ElasticLowLevelClient.cs
+++ b/src/Elasticsearch.Net/ElasticLowLevelClient.cs
@@ -46,7 +46,7 @@ namespace Elasticsearch.Net
 			if (!allow404 && contentType.IsNullOrEmpty()) return requestParams;
 
 			requestParams = requestParams ?? new TRequestParams();
-			if (requestParams.RequestConfiguration == null) requestParams.RequestConfiguration = new RequestConfiguration();
+			if (requestParams.RequestConfiguration == null) requestParams.RequestConfiguration = new RequestConfiguration { EnableHttpPipelining = Settings.HttpPipeliningEnabled };
 			if (allow404)
 				requestParams.RequestConfiguration.AllowedStatusCodes = new[] { 404 };
 			if (!contentType.IsNullOrEmpty() && requestParams.RequestConfiguration.ContentType.IsNullOrEmpty())

```

However, there's related issue in 5.x branch: methods 

- IElasticLowLevelClient.Get<T>
- IElasticLowLevelClient.Delete<T>
- IElasticLowLevelClient.XpackWatcherGetWatch<T>
- IElasticLowLevelClient.XpackWatcherDeleteWatch<T>

does not throw when IConnectionConfigurationValues.ThrowExceptions is set to true and http status code 404 is returned. Not sure whether a new issue should be created. There's a test to reproduce.

```
[Test]
public void GetDocumentThrowsOn404TestWhenConnectionConfiguredToThrow()
{
		var config = new ConnectionConfiguration()
				.ThrowExceptions();
		
		var client = new ElasticLowLevelClient(config);
		Assert.Throws<ElasticsearchClientException>(() => client.Get<byte[]>("non_existing_index", "test", "test"));
}
```

And here is a proposal to address the issue. In short, I changed api generation to **allow404: true** for HEAD method from Allow404 group (IElasticLowLevelClient.<object>Exists methods) because there's no sense in throwing in methods for checking the existence, and set **allow404: !Settings.ThrowExceptions** for other methods from Allow404 group in order to take into account this setting.
```
--- a/src/CodeGeneration/ApiGenerator/Views/ElasticLowLevelClient.Generated.cshtml
+++ b/src/CodeGeneration/ApiGenerator/Views/ElasticLowLevelClient.Generated.cshtml
@@ -59,7 +59,7 @@ namespace Elasticsearch.Net
 		{<text>		[Obsolete("Scheduled to be removed in 6.0, @method.ObsoleteMethodVersion removed this method from the rest specification")]
 </text>}
 		<text>public @Raw(method.ReturnType) @(method.FullName)@(Raw(method.ReturnTypeGeneric))(@Raw(method.Arguments))
-			where @method.CallTypeGeneric : class => this.@(requestMethod)@(Raw("<" + method.CallTypeGeneric +">"))(@method.HttpMethod, Url($"@(Raw(patchedUrl))"), @(method.FullName.Contains("Async") ? "cancellationToken, " : string.Empty)@(method.Parts.Any(pp=>pp.Name == "body") ? "body" : "null"), _params(requestParameters@(method.Allow404 ? ", allow404: true" :"")@(Raw(url.StartsWith("_cat") ? ", contentType: \"text/plain\", accept: \"text/plain\"" : ""))));
+			where @method.CallTypeGeneric : class => this.@(requestMethod)@(Raw("<" + method.CallTypeGeneric +">"))(@method.HttpMethod, Url($"@(Raw(patchedUrl))"), @(method.FullName.Contains("Async") ? "cancellationToken, " : string.Empty)@(method.Parts.Any(pp=>pp.Name == "body") ? "body" : "null"), _params(requestParameters@(method.Allow404 ? (method.HttpMethod == "HttpMethod.HEAD" ? ", allow404: true" : ", allow404: !Settings.ThrowExceptions") :"")@(Raw(url.StartsWith("_cat") ? ", contentType: \"text/plain\", accept: \"text/plain\"" : ""))));
 		</text>
 		}
 	}
```

**Comment by ivan-sam** [comment]
For branch 6.x I guess such a simple fix should work (method **ElasticLowLeveClient._params<TRequestParams>(TRequestParams requestParams, string contentType = null, string accept = null)**):

```
--- a/src/Elasticsearch.Net/ElasticLowLevelClient.cs
+++ b/src/Elasticsearch.Net/ElasticLowLevelClient.cs
@@ -45,7 +45,8 @@ namespace Elasticsearch.Net
 			if (contentType.IsNullOrEmpty()) return requestParams;
 
 			requestParams = requestParams ?? new TRequestParams();
-			if (requestParams.RequestConfiguration == null) requestParams.RequestConfiguration = new RequestConfiguration();
+			if (requestParams.RequestConfiguration == null)
+				requestParams.RequestConfiguration = new RequestConfiguration { EnableHttpPipelining = Settings.HttpPipeliningEnabled, ThrowExceptions = Settings.ThrowExceptions };
 			if (!contentType.IsNullOrEmpty() && requestParams.RequestConfiguration.ContentType.IsNullOrEmpty())
 				requestParams.RequestConfiguration.ContentType = contentType;
 			if (!accept.IsNullOrEmpty() && requestParams.RequestConfiguration.Accept.IsNullOrEmpty())
```

**Comment by russcam** [comment]
Thanks for the PR @ivan-sam 👍

**Comment by russcam** [comment]
@ivan-sam I need to have a further look at the 5.x branch

**Comment by russcam** [comment]
> does not throw when IConnectionConfigurationValues.ThrowExceptions is set to true and http status code 404 is returned. Not sure whether a new issue should be created. 

I've opened #3248

**Pull request merged**
