### PR TITLE
Fix for sniffing throwing error for multiple threads.

### PR DESCRIPTION
**Pull request by lostllama**
In using ES, I found that the following scenario could throw an error, and it seems to be down to the way the semaphores are handled. This is the scenario:

1) Thread A blocks the semaphore, sniffs, and releases it.
2) Thread B waits for the semaphore, A releases, B blocks, and then, not needing to sniff, simply returns.
3) Thread C waits for the semaphore, A releases, B blocks, and then C times out because B never released it.

My solution is two-fold:

1) Thread B will release the semaphore, so that C can enter.
2) In case Thread C times out before B can release, it checks if sniffing is needed before throwing the exception, and, if it isn't, it simply returns (as opposed to throwing the exception).

### CODE REVIEW

**Comment by russcam** [comment]
@lostllama this looks good; would you be able to add a test as well?

**Comment by lostllama** [comment]
Hi Russ

Maybe this evening :) I'm at work at the moment and beyond fixing the issue
(which was causing us a problem), I'm not sure they'd like me working on
tests in work time. I'll see what I can do when I get home.

John

**Comment by karmi** [comment]
Hi @lostllama, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch-net/pull/2221.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by lostllama** [comment]
@karmi I've made my e-mail address visible. It is the same e-mail address, however.

**Comment by lostllama** [comment]
@karmi I've done that now.

**Comment by russcam** [comment]
@lostllama I'll look at adding some tests for this; we have some in this area but looks like it didn't catch this.

**Comment by russcam** [comment]
I've added a test to verify that no pipeline exception is thrown, indicating that Thread B has released the `SemaphoreSlim`.

Thanks again for the PR, we're looking to put a release out this week so it will be included in that.

**Comment by lostllama** [comment]
@russcam Thanks :)

**Comment by russcam** [comment]
[This is now on nuget in 2.4.4](https://www.nuget.org/packages/NEST/2.4.4)

**Pull request merged**
