### PR TITLE
add support for the kv processor

### PR DESCRIPTION
**Pull request by Mpdreamz**

### CODE REVIEW

**Comment by Mpdreamz** [comment]
I was on the fence with `KVProcessor` since that would also mean having a `KV()` on `ProcessorsDescriptor` which looks a bit iffy :)

lmk if you object we can rename post merge.

**Comment by Mpdreamz** [comment]
ported to `master`

**Comment by russcam** [comment]
> I was on the fence with KVProcessor since that would also mean having a KV() on ProcessorsDescriptor which looks a bit iffy :)

yeah, `.KV()` is a bit funky. I don't have strong opinions about it to be honest 😄 @gmarz ?

**Comment by gmarz** [comment]
I'm good with KeyValue 👍

**Pull request merged**
