### PR TITLE
Added Min/MaxChildren to HasChildFilterDescriptor

### LINKED ISSUE #1505: HasChildFilterDescriptor lacks Min/MaxChildren Properties
I just wanted to try out min_children / max_children filter functionality of ES using a [HasChildFilterDescriptor](https://github.com/elastic/elasticsearch-net/blob/a139f054d3c6b669bbfcb758e12232f440bf04f8/src/Nest/DSL/Filter/HasChildFilterDescriptor.cs) and I noticed that, contrary to its [HasChildQueryDescriptor](https://github.com/elastic/elasticsearch-net/blob/4e44bfd575e023aea0a0693a0c9d4ea497363a42/src/Nest/DSL/Query/HasChildQueryDescriptor.cs) counterpart, the Filter does not have the Min/MaxChildren Properties, even though [ES seems to support these in Filters](https://www.elastic.co/guide/en/elasticsearch/reference/1.4/query-dsl-has-child-filter.html), too.

### PR DESCRIPTION
**Pull request by jbattermann**
.. correspondingly as it was implemented in HasChildQueryDescriptor.cs. This fixes #1505

### CODE REVIEW

**Comment by jbattermann** [comment]
Yikes - CLA signed and sent.

**Comment by Mpdreamz** [comment]
Awesome! thanks for taking the time to submit a PR @jbattermann 

Small nag mind installing the editorconfig visual extension (https://visualstudiogallery.msdn.microsoft.com/c8bccfe2-650c-4b42-bc5c-845e21f96328) and reformatting your changes? http://editorconfig.org/ allows you to have per project indent/line ending settings.

**Comment by jbattermann** [comment]
Ahh I had missed that one, too.. but sure thing @Mpdreamz ! Updated the PR after installing the Extension and performing a 'Format Document' on the changed file. Hope it looks good now :)

**Comment by Mpdreamz** [comment]
LGTM :+1: ty for taking the time to fix up indentation, much appreciated :smile:

**Pull request merged**
