### PR TITLE
Longitude <- Longtitude, causes Geo deserialization fail

### PR DESCRIPTION
**Pull request by robrich**

### CODE REVIEW

**Comment by robrich** [comment]
I signed it

**Comment by Mpdreamz** [comment]
Thanks @robrich! Will pull this in when we do a bug fix release for NEST. It still needs some backwards compatibility fixes.

**Comment by russcam** [comment]
I'm tidying up the branches to rename (branch move and delete)
- `2.0` to `master`
- `develop` (current 1.x client) to `1.x`

and as a consequence, closed this PR as a result of deleting the remote `develop` branch, sorry! I've reinstated the branch to keep track of the open PRs but feel free to close this PR and open a new one with the change against  `1.x` :smile:

**Comment by russcam** [comment]
LGTM!

**Pull request merged**
