### PR TITLE
fix #2561  HttpClientHandler.MaxConnectionsPerServer not always available

### LINKED ISSUE #2561: .Missing() for Term-aggregation of int-field
**NEST/Elasticsearch.Net version**: 5.0.1

**Elasticsearch version**: 5.1.2

**Description of the problem including expected versus actual behavior**:

When specifying `.Missing()` for Term-aggregation of integer-fields elastic reponds with a confusing error. 
It appears elastic 5 is stricter on types for missing-values in aggregations. `"missing":-1` works, but not `"missing":"-1"`.

**Steps to reproduce**:

```c
void Main()
{
	var client = new ElasticClient(new Uri("http://localhost:9200"));
	
	client.CreateIndex("fooindex", c => c.Settings(s => s.NumberOfShards(1).NumberOfReplicas(0))
		.Mappings(ms => ms.Map<Foo>(m => m.AutoMap()))
	);
	
	var resp = client.Search<Foo>(s => s
		.Index("fooindex")
		.Aggregations(a => a
			.Terms("a", t => t.Field(b => b.SomeInt)
				.Missing("-1") // need overload that takes int?
			)
		)
	);
	
	// writes: Field [someInt] of type [integer] does not support custom time zones
	Console.WriteLine(resp.ServerError.Error.RootCause.First().Reason); 
}

public class Foo
{
	public int Id { get; set; }
	public int SomeInt { get; set; }
}
```

### LINKED ISSUE #2581: Error in Xamarin.Droid when using ElasticSearch.net NEST
**NEST/Elasticsearch.Net version**: 5.0.1

**Elasticsearch version**: 5

**Description of the problem including expected versus actual behavior**:
Querying elasticsearch causes error HttpClientHandler.set_MaxConnectionsPerServer not found error.  Before upgrading to latest version, code was working successfully.

**Steps to reproduce**:
 1.run client.Search(s => s.
														 Index(index).
														 Type(type).
														 From(0).
														 Size(50).
														 Query(q => q1)
														);
 2. Displays error from above
 3.

**Provide `ConnectionSettings` (if relevant)**: Default settings, with just URL defined

**Provide `DebugInformation` (if relevant)**:
Elasticsearch.Net.UnexpectedElasticsearchClientException: Method 'HttpClientHandler.set_MaxConnectionsPerServer' not found. ---> System.MissingMethodException: Method 'HttpClientHandler.set_MaxConnectionsPerServer' not found.
  at Elasticsearch.Net.HttpConnection+<>c__DisplayClass2_0.<GetClient>b__0 (Int32 h) [0x00000] in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:47
  at System.Collections.Concurrent.ConcurrentDictionary`2[TKey,TValue].GetOrAdd (System.Collections.Concurrent.TKey key, System.Func`2 valueFactory) [0x00037] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/collections/Concurrent/ConcurrentDictionary.cs:1049
  at Elasticsearch.Net.HttpConnection.GetClient (Elasticsearch.Net.RequestData requestData) [0x00042] in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:45
  at Elasticsearch.Net.HttpConnection.Request[TReturn] (Elasticsearch.Net.RequestData requestData) [0x00000] in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:64
  at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TReturn] (Elasticsearch.Net.RequestData requestData) [0x00023] in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:400
  --- End of inner exception stack trace ---
  at Elasticsearch.Net.Transport`1[TConnectionSettings].Request[TReturn] (HttpMethod method, System.String path, Elasticsearch.Net.PostData`1 data, IRequestParameters requestParameters) [0x0011a] in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Transport\Transport.cs:89
  at Elasticsearch.Net.ElasticLowLevelClient.DoRequest[T] (HttpMethod method, System.String path, Elasticsearch.Net.PostData`1 data, IRequestParameters requestParameters) [0x00000] in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\ElasticLowLevelClient.cs:61
  at Elasticsearch.Net.ElasticLowLevelClient.Search[T] (System.String index, System.String type, Elasticsearch.Net.PostData`1 body, System.Func`2 requestParameters) [0x00000] in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\ElasticLowLevelClient.Generated.cs:7011
  at Nest.LowLevelDispatch.SearchDispatch[T] (IRequest`1 p, Elasticsearch.Net.PostData`1 body) [0x00129] in C:\Users\russ\source\elasticsearch-net-5.x\src\Nest\_Generated\_LowLevelDispatch.generated.cs:2758
  at Nest.ElasticClient+<>c__DisplayClass525_0`2[T,TResult].<Search>b__0 (ISearchRequest p, Elasticsearch.Net.PostData`1 d) [0x00000] in C:\Users\russ\source\elasticsearch-net-5.x\src\Nest\Search\Search\ElasticClient-Search.cs:74
  at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse] (Nest.TRequest request, System.Func`3 responseGenerator, System.Func`3 dispatch) [0x00031] in C:\Users\russ\source\elasticsearch-net-5.x\src\Nest\ElasticClient.cs:57
  at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse] (Nest.TRequest request, System.Func`3 dispatch) [0x00000] in C:\Users\russ\source\elasticsearch-net-5.x\src\Nest\ElasticClient.cs:47
  at Nest.ElasticClient.Search[T,TResult] (ISearchRequest request) [0x00014] in C:\Users\russ\source\elasticsearch-net-5.x\src\Nest\Search\Search\ElasticClient-Search.cs:72
  at Nest.ElasticClient.Search[T] (ISearchRequest request) [0x00000] in C:\Users\russ\source\elasticsearch-net-5.x\src\Nest\Search\Search\ElasticClient-Search.cs:66
  at Nest.ElasticClient.Search[T,TResult] (System.Func`2 selector) [0x00000] in C:\Users\russ\source\elasticsearch-net-5.x\src\Nest\Search\Search\ElasticClient-Search.cs:62
  at Nest.ElasticClient.Search[T] (System.Func`2 selector) [0x00000] in C:\Users\russ\source\elasticsearch-net-5.x\src\Nest\Search\Search\ElasticClient-Search.cs:56
  at ProviderPing.ProviderLoginAPI.GetProviderLoginModelFromES (System.String optum_id) [0x00082] in /Users/pphilip1/Projects/ExternalMVP/providerpingping/ProviderPing/Network/ProviderLoginAPI.cs:39
  at ProviderPing.Droid.ProviderLogin.<ProcessSuccessfulLogin>m__0 (System.Object state) [0x00017] in /Users/pphilip1/Projects/ExternalMVP/providerpingping/Droid/Fragments/Login/ProviderLogin.cs:226
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x0000e] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/threading/threadpool.cs:1307
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) [0x0008d] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/threading/executioncontext.cs:957
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) [0x00000] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/threading/executioncontext.cs:904
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x0002a] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/threading/threadpool.cs:1284
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00096] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/threading/threadpool.cs:857
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/threading/threadpool.cs:1212

### PR DESCRIPTION
**Pull request by Mpdreamz**
Make the call to HttpClientHandler.MaxConnectionsPerServer optional if our ConnectionLimit setting is greater than zero, we also try catch and throw a nice exception message so folks know how to fix it may they run into this

fix #2581

### CODE REVIEW

**Comment by saintpaul1984** [comment]
I haven't tested the fix, but looking at the modified code:
  if (requestData.ConnectionSettings.ConnectionLimit > 0)
			{
				try
				{
					handler.MaxConnectionsPerServer = requestData.ConnectionSettings.ConnectionLimit;
				}
				catch (MissingMethodException e)
				{
					throw new Exception(MissingConnectionLimitMethodError, e);
				}
			}

I will still see the issue, because

 settings.ConnectionLimit(-1) produces an error since it requires that the value be greater than 0.  (We can't set to -1 as the error comment suggests??)

**Comment by Mpdreamz** [comment]
@saintpaul1984 you are absolutely right, fixing this now

**Comment by saintpaul1984** [comment]
Ok I apologize if this is a stupid question, but now that the issue has been fixed how do I get the latest version in my xamarin app.  I "updated" NEST and elasticsearch.net but that didn't seem to bring in the change?

**Comment by gmarz** [comment]
Ported this to 2.x, 5.x and master

**Comment by gmarz** [comment]
@saintpaul1984 we haven't released a new version yet :)  Sit tight, looking to release shortly.

**Pull request merged**
