### PR TITLE
Added missing visitor implementations

### PR DESCRIPTION
**Pull request by jonyadamit**
Forgot about these with #1967 . Maybe some tests to ensure correlation are in order?
Installed EditorConfig and now it shows the entire file as deletions and additions. Don't know why.

### CODE REVIEW

**Comment by russcam** [comment]
Thanks for the PR @jonyadamit; I added a unit test to assert we have `Visit()` methods for all Aggregations :+1:

**Comment by jonyadamit** [comment]
@russcam since #1967 was merged into `master` as well, I believe so should this one along with your test.  What's the deal with version 5 anyway?   Why skip 3 and 4, and how do you choose what gets merged in there and what's not?

**Comment by russcam** [comment]
Yep, I'll merge it into `master` today; I had plans to, was just getting later in the day here in Australia yesterday :smile: 

The current plan is to number the next major version of NEST and Elasticsearch.Net as version 5.x to align with the next major version of Elasticsearch, the intention being that major versions of the client are compatible with major versions of Elasticsearch.

**Comment by jonyadamit** [comment]
I was wondering why Elasticsearch itself is being versioned 5. Couldn't find an explanation anywhere and my best guess currently is that it's done to match the lucene version (?)..

**Comment by russcam** [comment]
_Close_  :smile:  It's to align versions across the Elastic stack

- Elasticsearch
- Logstash
- Kibana
- Beats

etc... and to reduce the burden in understanding the compatibility across products i.e. _Elasticsearch 2.3.0 is compatible with Kibana 4.5.0 but not with Kibana x_. Version 5 was decided as it is the next nearest major version across all products.

You can find out more details in the [Elasticon video "What's Evolving in Elasticsearch"](https://www.elastic.co/elasticon/conf/2016/sf/whats-evolving-in-elasticsearch) and also in the [Opening Keynote](https://www.elastic.co/elasticon/conf/2016/sf/opening-keynote) :+1: 

This PR has been [cherry-picked for merge into `master` now](https://github.com/elastic/elasticsearch-net/pull/1992).

**Pull request merged**
