### PR TITLE
Add relation to geo_shape queries

### PR DESCRIPTION
**Pull request by russcam**
- Add `Relation` to geo_shape queries

  GeoShapeRelation was in the codebase but looks like it was missed in the geo refactoring

- Add `contains` to geoshape relations.

Needs to be forward ported to 5.x

### CODE REVIEW

**Comment by gmarz** [comment]
LGTM

**Comment by michaelbudnik** [comment]
Any ETA on the release which will contain this fix?

**Comment by gmarz** [comment]
Merged to 2.x so we can push out a release today.  Still needs porting to `master` though @forloop.

**Comment by gmarz** [comment]
@michaelbudnik [2.4.3](https://github.com/elastic/elasticsearch-net/releases/tag/2.4.3) is now out on nuget.org

**Comment by michaelbudnik** [comment]
@gmarz Many thanks for this!

**Comment by russcam** [comment]
Ported to master in e28e03e86cffc3cef1bb41c195c7576ae5e60257 :+1:

**Pull request merged**
