### PR TITLE
Change type of took field in responses.

### PR DESCRIPTION
**Pull request by maeserichar**
This PR copes with the changes needed for #2308.

I have hunted down the rest of int "Took" fields, and modified some auxiliar classes that uses said field.

### CODE REVIEW

**Comment by gmarz** [comment]
@maeserichar huge thanks for this PR.  Unfortunately this breaks backwards compatibility on the 2.x branch though.  Would you mind re-targeting this PR for master?  We'll have to come up with a modified approach for 2.x

**Comment by maeserichar** [comment]
@gmarz What would be the process to retarget the PR (I'm kind of a newbie in git/github flow)?

For the modified approach for the 2.x branch, what can I do about that?

Regards,

**Comment by gmarz** [comment]
> What would be the process to retarget the PR (I'm kind of a newbie in git/github flow)?

Since this is a relatively small change, the simplest way is probably to just pull down master, make the changes again, and open a new PR against master.

> For the modified approach for the 2.x branch, what can I do about that?

This is unfortunate, but we can introduce a new property that is of type long and move the the JsonProperty attribute over to it.  Then mark the original `Took` property as obsolete (with a verbose message) and change its getter to cast and return the new long property.  If the value exceeds int.MaxValue, then we can let it wrap around...but the obsolete warning message should make it clear that this is a possibility and why the new property should be used instead.  Thoughts?  Open to suggestions here.  /cc @elastic/microsoft

**Comment by maeserichar** [comment]
@gmarz Ok, I have sent #2324 with the changes to the Master branch. I will try to submit a first version of the discussed changes over the 2.x branch.

Thanks!

**Pull request closed without merging**
