### PR TITLE
Add Pause/Resume Auto Follower APIs

### PR DESCRIPTION
**Pull request by codebrain**
Implements: https://github.com/elastic/elasticsearch/pull/47510

### CODE REVIEW

**Comment by codebrain** [comment]
> Missing integration tests - could add steps to `CrossClusterReplicationAutoFollowTests`?

The only issue is that the test suite is marked with a `BlockedByIssue` attribute, so this suite doesn't run. I can add some placeholder tests in?

**Comment by Mpdreamz** [comment]
The `BlockedByIssue` does not seem relevant anymore

**Comment by codebrain** [comment]
OK, the issue with the integration tests is "could not determine the license type for cluster [remote-cluster]".

This fails as the remote cluster is not actually running, but is provided as settings only (https://github.com/elastic/elasticsearch-net/blob/27f44edec582033092bb82f422d633f96ebec09c/src/Tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs#L96).

Will open an issue for this.

**Comment by codebrain** [comment]
Opened: https://github.com/elastic/elasticsearch-net/issues/4284

**Comment by codebrain** [comment]
Ported to `master`

**Pull request merged**
