### PR TITLE
Add Percent metric in OperatingSystemStats

### PR DESCRIPTION
**Pull request by TheFireCookie**
Add Percent metric in OperatingSystemStats to solve this issue:

https://github.com/elastic/elasticsearch-net/issues/2181

### CODE REVIEW

**Comment by gmarz** [comment]
@TheFireCookie out of curiosity what version of ES are you running? I tested against version 2.3.4 and the property is `os.cpu_percent`, not `os.percent`.

Also, would be great if you could add an assertion to the integration test here: https://github.com/elastic/elasticsearch-net/blob/2.x/src/Tests/Cluster/NodesStats/NodesStatsApiTests.cs#L98

**Comment by TheFireCookie** [comment]
Sorry, I just went on the doc of ElasticSearch there: https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#os-stats

I'll correct my pull request and write a test then.

**Comment by gmarz** [comment]
:+1: thanks!  One last request...would you mind rebasing and squashing this PR to a single commit?

**Comment by TheFireCookie** [comment]
The new one: https://github.com/elastic/elasticsearch-net/pull/2186

**Pull request closed without merging**
