### PR TITLE
Added min to NestedScoreMode

### PR DESCRIPTION
**Pull request by davemcdermid**

### CODE REVIEW

**Comment by davemcdermid** [comment]
I signed the CLA before submitting the pull request, is there anything else I need to do? Has it associated with my github account properly?

**Comment by Mpdreamz** [comment]
Nope looking good! Thank you for the PR @davemcdermid 👍 

Will pull this in tomorrow.

**Comment by Mpdreamz** [comment]
both `master` and `5.x` already had this fix so no need to forward merge:

https://github.com/elastic/elasticsearch-net/blob/5.x/src/Nest/QueryDsl/Joining/Nested/NestedScoreMode.cs
https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/QueryDsl/Joining/Nested/NestedScoreMode.cs

**Comment by davemcdermid** [comment]
Great, thanks :)

**Pull request merged**
