### PR TITLE
Small styling fix

### PR DESCRIPTION
**Pull request by nikitasavinov**

### CODE REVIEW

**Comment by russcam** [comment]
@nikitasavinov have you signed the [CLA](http://www.elasticsearch.org/contributor-agreement/)?

**Comment by russcam** [comment]
@nikitasavinov have you signed the CLA at https://www.elastic.co/contributor-agreement?

**Comment by nikitasavinov** [comment]
@russcam Sorry for such a long reply. I'm sure I did (about four days ago)

**Comment by nikitasavinov** [comment]
@russcam Sorry for such a long reply. I see my PR is not relevant anymore so closing it. Good luck and thanks for the great project!

**Comment by russcam** [comment]
No worries @nikitasavinov. If you see any other typos in the future, please feel free to submit a PR; now that the CLA has been signed, merging your PRs will be much smoother 😄

**Pull request closed without merging**
