### PR TITLE
Add histogram datatype

### LINKED ISSUE #4358: Add HistogramProperty
Relates: #4341 

Documentation: https://www.elastic.co/guide/en/elasticsearch/reference/7.6/histogram.html

New Histogram field mapper that supports percentiles aggregations. elastic/elasticsearch#48580 (issue: elastic/elasticsearch#48578)

### PR DESCRIPTION
**Pull request by russcam**
This commit adds the histogram datatype to the client. The histogram datatype
is available in Elasticsearch 7.6.0+ with at least a basic license level

Closes #4358

### CODE REVIEW

**Comment by russcam** [comment]
I did consider adding a type to be able to index histogram values and counts. Thoughts?

**Comment by codebrain** [comment]
The docs (https://www.elastic.co/guide/en/elasticsearch/reference/7.x/histogram.html) indicate the format for indexing is quite simple:

```
PUT my_index/_doc/1
{
  "my_text" : "histogram_1",
  "my_histogram" : {
      "values" : [0.1, 0.2, 0.3, 0.4, 0.5], 
      "counts" : [3, 7, 23, 12, 6] 
   }
}
```

I think a type to index this is probably worth it and quite simple to implement?

**Comment by Mpdreamz** [comment]
- Test failures are fixed in `7.x` upstream

A type used for indexing would be good, however we would also need to make sure it works well with `Json.NET` as the source serializer.

**Comment by russcam** [comment]
> I think a type to index this is probably worth it and quite simple to implement?

It being a simple type was my reason to not implement it 😄 Could add one in a follow up PR?

**Pull request merged**
