### PR TITLE
Add IgnoreUnmapped to GeoDistanceQuery, GeoBoundingBoxQuery and GeoPo…

### PR DESCRIPTION
**Pull request by alrz1999**
…lygonQuery.

### CODE REVIEW

**Comment by alrz1999** [comment]
As it mentioned in Elasticsearch documents, these kinds of request can support `IgnoreUnmapped` which is useful for searching on multiple indices. But as I tried to set that to `true` I found out it doesn't exist.
[GeoBoundingBoxQuery](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-bounding-box-query.html#_ignore_unmapped)
[GeoDistanceQuery](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-distance-query.html#_ignore_unmapped_2)
[GeoPolygonQuery](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-polygon-query.html)

**Comment by stevejgordon** [comment]
Thanks for submitting this @alrz1999. Very much appreciated! Would you be able to retarget this to `7.x`? The master branch is going to see some major changes in 8.0 as we move to code generating a lot of these types. It should be largely fixed by that work when we're ready to merge it. These should make their way into a `7.x` release ideally. If you don't have time I can pick it up at some point.

**Comment by alrz1999** [comment]
Thanks for reviewing. I opened another pull request to add it on `7.x`.

**Comment by stevejgordon** [comment]
Closing this as merged into `7.x` in another PR.

**Pull request closed without merging**
