### PR TITLE
Update TargetFrameworks

### LINKED ISSUE #8050: Remove netcoreapp3.1 and net5.0 from TargetFrameworks and add net8.0
**Is your feature request related to a problem? Please describe.**
Currently, I see in the csproj files `<TargetFrameworks>netstandard2.0;net461;netstandard2.1;netcoreapp3.1;net5.0;net6.0</TargetFrameworks>`

**Describe the solution you'd like**
Remove `netcoreapp3.1` and `net5.0` and add `net8.0`.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by gpetrou**
Resolves #8050.

### CODE REVIEW

**Comment by gpetrou** [comment]
I used `nuget restore -ForceEvaluate` to update the packages.lock.json files.

**Comment by flobernd** [comment]
Seems like the "Unified Release / Assemble" workflow is failing because of the Docker container using the wrong .NET SDK version.

**Comment by flobernd** [comment]
Thanks for updating!

I think there is/was a bug in the way we pass the argument in the Docker commandline:
https://github.com/elastic/elasticsearch-net/blob/4a6b9e8ebb443f26d3ce9cdfa494292397b4052c/.ci/make.sh#L136

**Comment by flobernd** [comment]
Thanks again for updating. Seems like we are going down a rabbithole... The newer SDKs seem to use different temp paths which causes building the docker image to fail.

**Comment by gpetrou** [comment]
> The newer SDKs seem to use different temp paths which causes building the docker image to fail.

I think we need to append the user name at the end of the `NuGetScrarch` folder name. If I understand correctly, this should be `user`.
https://learn.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders

**Comment by flobernd** [comment]
Maybe we can just set the `NUGET_SCRATCH` environment variable to `/tmp/NuGetScratch` to restore the old behavior. Inside the Docker container we only have a single active user anyways.

**Comment by flobernd** [comment]
Looking good now! Thanks again for the PR and the updates. I'll merge on Monday and include the changes in the next patch release.

**Review by flobernd — APPROVED** [review]
LGTM! Thank you 🙂

**Comment by landlord-matt** [comment]
@flobernd Both .NET 7 and .NET 8 focused on JSON serialisation performance. Did you notice any difference?

Will the patch release also target Elasticsearch 8.6? When do you expect the patch release?

**Comment by flobernd** [comment]
@landlord-matt I don't think there will be any noticeable performance benefits as most of the optimizations are related to the codegen features which we don't use yet (they require code changes).

The patch will only target 8.12, but you should be able to update your 8.6 library to 8.12.1 when it's released. I think we had no major breaking changes since then.

A patch release will happen until end of March.

**Pull request merged**
