### PR TITLE
Generate low level client code for 7.12

### PR DESCRIPTION
**Pull request by stevejgordon**

### CODE REVIEW

**Review by Mpdreamz — CHANGES_REQUESTED** [review]
```
/home/vsts/work/1/s/src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.TextStructure.cs(61,10): error CS0246: The type or namespace name 'Format' could not be found (are you missing a using directive or an assembly reference?) 
```

**Comment by stevejgordon** [comment]
@Mpdreamz Oops! I had a couple of issues generating originally and committed the one without that fixed type name. I've fixed it again and re-generated.

**Review by Mpdreamz — APPROVED** [review]
LGTM!

**Comment by stevejgordon** [comment]
Will investigate the Linux failure on Jenkins before merging.

**Pull request merged**
