### PR TITLE
Invert document generation so it is not run by default.

### LINKED ISSUE #3674: Changes to build scripts
- Invert the `skipdocs` default parameter, so doc generation is always skipped
- Remove the IL rewriting for `7.x`

### PR DESCRIPTION
**Pull request by codebrain**
To generate documentation include the "gendocs" argument in the build command line, e.g.

`build.bat gendocs`

Fixes #3674

### CODE REVIEW

**Comment by codebrain** [comment]
> I think we should still run docs when running with the default target e.g just calling `./build.sh` or `build.bat` so that we can easily gen the docs as part of a PR.

Ah, I was thinking that we remove it altogether and then if you want to generate docs you write:

`build.bat gendocs`

Does that seem reasonable @Mpdreamz ?

**Comment by Mpdreamz** [comment]
`build.sh` or `build.bat` should be the command we run before submitting a PR to validate the build beyond actual compilation.

I think its best if the docs gen come through then as well.

**Comment by Mpdreamz** [comment]
Updated and rebased this PR and made `gendocs` enabled when using the default `build` target

**Comment by russcam** [comment]
LGTM. Merging this in

**Pull request merged**
