### PR TITLE
Improvement/build

### PR DESCRIPTION
**Pull request by Mpdreamz**
- Normalize module vs type usages in fsx files
- unit methods now all in Method() = form
- cleaned up build.bat and its skiptests leniency, now only accepted as
  the first argument
- Improved usage notice in build.bat
- Building now checks if `dotnet.exe` resolves to using the proper SDK
- Moved to DotNetCli FAKE helper (#2395)
- Separated Projects and Tooling out of Paths.fsx
- Now have a truly quick compile target
  `build quick [test_filter]` does an incremental build and runs the
  unit tests from the bin output folder. it also skips paket.
- moved global.json to the root of repos
- unit tests now parallizes over all tests ignoring all clusters
  rather then piggy backing on xunit which we do in 5.x (our own routine
  is 10+seconds faster) or on the integration routine (which we
  currently do in master)

### CODE REVIEW

**Comment by Mpdreamz** [comment]
@gmarz do you also get this after callinig `build` first? Had to upgrade to a later version of FAKE and `test` skips restore.

**Comment by gmarz** [comment]
I did try calling `build` initially and was hitting the same error.  Just did a `git clean -fxd` and ran `build` again and now I'm hitting

```
build.bat: target="build" version= esversions= skiptests=0 apiKey="<empty>" feed="elasticsearch-net" escluster= testfilter=
The system cannot find the path specified.
```

**Comment by gmarz** [comment]
Looks like [this line](https://github.com/elastic/elasticsearch-net/blob/improvement/build/build.bat#L40) is incorrectly setting SKIPPAKET

**Comment by gmarz** [comment]
Sorry, it's not incorrectly setting SKIPPAKET.  It's just that we never run paket restore for the first time.  I'm not sure if SKIPPAKET is really useful, since bootstrapping is always required whether we're running "quick" or not.

**Comment by Mpdreamz** [comment]
Updated this PR with some clean checkout and mixing regular with quick builds on the command line resiliency changes.

**Comment by gmarz** [comment]
LGTM!

**Comment by Mpdreamz** [comment]
ported to `2.x` and `master`

**Pull request merged**
