### PR TITLE
Fixes incorrect reference in documentation

### PR DESCRIPTION
**Pull request by MEmanuelsson**
Fixes incorrect reference to "MyFirstCustomJsonNetSerializer" in documentation

### CODE REVIEW

**Review by stevejgordon — CHANGES_REQUESTED** [review]
This change will need to be made at source in `CustomSerialization.doc.cs` which is used to generate this asciidoc file using `.\build.bat documentation`.

**Comment by stevejgordon** [comment]
Thanks for submitting this PR @MEmanuelsson. This is a generated file so the change would need to be made in `CustomSerialization.doc.cs` instead. If you're up for that, could you please amend this PR. You can run the docs generator afterwards to produce the asciidoc. If you're unable to make that change, no worries. Please let me know and I can close this and open a PR with the fix into the cs file.

**Comment by MEmanuelsson** [comment]
No problem @stevejgordon, pushed an update to `CustomSerialization.doc.cs` just now. 

Ran `.\build.bat documentation` after the update to verify the change, this also results in some other asciidoc-files being updated but decided not to push these updates to the repo, right or wrong? 

image

**Comment by stevejgordon** [comment]
This is perfect, thanks @MEmanuelsson! You made the correct call on the other generator changes. Some of those went into the branch yesterday and the deletions is a bug. I'll merge this in and handle backporting this to our other branches. Your help is very much appreciated.

**Pull request merged**
