### PR TITLE
Set MaxRetryException on task in RetryRequestAsync

### LINKED ISSUE #1645: MaxRetryException thrown from RequestHandlerAsync is not catchable
`RetryRequestAsync` calls `ThrowMaxRetryExceptionWhenNeeded`, but returns a `Task`.  If you try to `await` this method, the exception is not catchable because it is thrown rather than set on the `Task`.

### PR DESCRIPTION
**Pull request by Entroper**
Fixes #1645.

### CODE REVIEW

**Comment by Entroper** [comment]
FYI, I'm working with my employer on the CLA.

**Comment by Mpdreamz** [comment]
Thanks for looking into this and sending the PR :+1: We are currently focused on getting 2.0 alpha1 out the door after that doing a bug fix release for 1.x is the next top priority so it might be some days before one of us can review.

**Comment by russcam** [comment]
Hey @Entroper, I'm tidying up the branches to rename (branch move and delete)
- `2.0` to `master`
- `develop` (current 1.x client) to `1.x`

and as a consequence, closed this PR as a result of deleting the remote `develop` branch, sorry! I've reinstated the branch to keep track of the open PRs but feel free to close this PR and open a new one with the change against  `1.x` :smile:

**Comment by Entroper** [comment]
Opened #1702 against `1.x`.

**Pull request closed without merging**
